version: 1.0.{build}
skip_tags: true
clone_folder: C:\Projects\MRTD.NET\
configuration: Debug
environment:
  COVERALLS_REPO_TOKEN:
    secure: XWiL6LEQaVhFTVjsb0NUG37Zdv5uenF7aKl0Vhkre446M8zElJKfqL8R+RuvLGlp
before_build:
  - nuget restore ".\MRTD.NET.sln"
build:
  project: .\MRTD.NET.sln
  publish_nuget: true
  verbosity: minimal
test_script:
- ps: >-
    .\packages\OpenCover.*\tools\OpenCover.Console.exe -register:user -target:nunit3-console.exe "-targetargs:""SmartCardApi\bin\$env:CONFIGURATION\SmartCardApi.dll" "DemoApp\bin\$env:CONFIGURATION\DemoApp.dll"" " -filter:"+[SmartCardApi*]*" -output:opencoverCoverage.xml

    $coveralls = (Resolve-Path "packages/coveralls.net.*/tools/csmacnz.Coveralls.exe").ToString()
    
    $env:APPVEYOR_BUILD_NUMBER
    
    & $coveralls --opencover -i opencoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --useRelativePaths --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_BUILD_NUMBER --serviceName appveyor

before_package:
- ps: "$projectName = \"SmartCardApi\"\n\n$csprojPathTemplate = \".\\PROJECT_NAME\\PROJECT_NAME.csproj\"\n$csprojPath = $csprojPathTemplate -replace \"PROJECT_NAME\", $projectName\n\nfunction replaceSymbolsInFile($regex, $path) \n{   \n    (Get-Content $path) -replace $regex,'' | out-file $path \n}\n\n$testCSFilesRegex = '\\n(\\W+|\\t+)<Compile Include=\"(\\S+\\.test\\.cs)\" />\\r'\nreplaceSymbolsInFile $testCSFilesRegex $csprojPath"
deploy:
- provider: NuGet
  api_key:
    secure: wDCNNKlK1++DShgVeMDQEyVtIu4GqTCTiMHgLXCRf9u7PWZCo3N531zyLMLxKo8n
  skip_symbols: true
notifications:
- provider: GitHubPullRequest
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
