version: 1.0.{build}
clone_folder: C:\Projects\MRTD.NET\
before_build:
  - nuget restore
build:
  verbosity: minimal
notifications:
- provider: GitHubPullRequest
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true